### PR TITLE
Fix sporadic invalid zip from memory

### LINKED ISSUE #36: BUG: Zip file output sometimes corrupted on Linux
## Overview

Tests for reading from `.zip` file store sometimes fail. Exact cause is unclear at the moment.

First CI run (failed)
https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5716549674/job/15488329023?pr=35

Second CI run, no changes (passing):
https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5716549674/job/15490659684?pr=35

## Workaround

Re-running CI seems to work for now.

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #36. This exposed a bug in tensorstore implementation which was fixed by https://github.com/InsightSoftwareConsortium/tensorstore/commit/aaf8b85ad123e10482f6917f9880d33972814b53.

### CODE REVIEW

**Comment by dzenanz** [comment]
Failure was due to `Error message was: Could not resolve host: open.cdash.org`. We should re-run the failing tests once the option is available.

**Comment by dzenanz** [comment]
Tests pass on the CI, and locally with the rebased tensorstore. This is ready for merge.

File: include/itkOMEZarrNGFFImageIO.h [hunk 1]
```diff
@@ -231,6 +239,11 @@ class IOOMEZarrNGFF_EXPORT OMEZarrNGFFImageIO : public ImageIOBase
   int                m_TimeIndex = INVALID_INDEX;
   int                m_ChannelIndex = INVALID_INDEX;
   AxesCollectionType m_StoreAxes;
+
+  const static unsigned m_EmptyZipSize = 22;
```
Comment (tbirdso) [inline include/itkOMEZarrNGFFImageIO.h:243]: Could you please add a comment clarifying how this value is derived?

Not required, but could rename to reflect that this is a static constant: `static constexpr unsigned EMPTY_ZIP_SIZE = 22;`

File: include/itkOMEZarrNGFFImageIO.h [hunk 2]
```diff
@@ -231,6 +239,11 @@ class IOOMEZarrNGFF_EXPORT OMEZarrNGFFImageIO : public ImageIOBase
...
+  char                  m_EmptyZip[m_EmptyZipSize] = "PK\x05\x06"; // the rest is filled with zeroes
```
Comment (tbirdso) [inline include/itkOMEZarrNGFFImageIO.h:244]: How is this derived? Required header for zip file format? Could a descriptive comment please be added?

File: src/itkOMEZarrNGFFImageIO.cxx [hunk 3]
```diff
@@ -807,8 +812,13 @@ OMEZarrNGFFImageIO::Write(const void * buffer)
     itkExceptionMacro("Unsupported component type: " << GetComponentTypeAsString(this->GetComponentType()));
   }
 
-  // Create a new context to close the open zip handles
-  tsContext = tensorstore::Context::Default();
+  if (m_FileName.substr(m_FileName.size() - 4) == ".zip" || m_FileName.substr(m_FileName.size() - 7) == ".memory")
+  {
+    // Attempt to read a non-existent file from the in-memory zip to close the current one
```
Comment (tbirdso) [inline src/itkOMEZarrNGFFImageIO.cxx:817]: Is this a workaround for an existing Tensorstore issue?

File: include/itkOMEZarrNGFFImageIO.h [hunk 4]
```diff
@@ -100,6 +100,14 @@ class IOOMEZarrNGFF_EXPORT OMEZarrNGFFImageIO : public ImageIOBase
     size_t size;
   };
 
+  /** Construct a "magic" file name from the provided bufferInfo. */
+  static std::string
+  MakeMemoryFileName(const itk::OMEZarrNGFFImageIO::BufferInfo & bufferInfo)
```
Comment (tbirdso) [inline include/itkOMEZarrNGFFImageIO.h:105]: Agree with the decision to make this a public helper function 👍

**Review by tbirdso — COMMENTED** [review]
Very nice, thanks for tracking down this issue @dzenanz !

Could you please clarify how this relates to tensorstore fork rebase efforts at https://github.com/InsightSoftwareConsortium/tensorstore/pull/1 ? Is this a workaround for an issue in the previous fork `master` branch? Will the underlying issue still exist after `InsightSoftwareConsortium/tensorstore@master` is rebased?

**Comment by tbirdso** [comment]
I see now this note in https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/issues/36#issuecomment-1702784772 clarifying the relationship to the underlying Tensorstore issue. 👍

File: src/itkOMEZarrNGFFImageIO.cxx (hunk 3 above)
Comment (dzenanz) [reply src/itkOMEZarrNGFFImageIO.cxx:817]: I don't know whether the issue is in tensorstore, or in our zip addition to it.

**Review by tbirdso — APPROVED** [review]
LGTM
